# Generated by Django 4.2.6 on 2024-01-01 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_id', models.CharField(max_length=50, unique=True)),
                ('trip_type', models.CharField(choices=[('interstate', 'Interstate Commerce'), ('intrastate', 'Intrastate Commerce')], default='interstate', max_length=20)),
                ('state', models.CharField(blank=True, max_length=2, null=True)),
                ('current_location', models.CharField(max_length=255)),
                ('pickup_location', models.CharField(max_length=255)),
                ('dropoff_location', models.CharField(max_length=255)),
                ('current_cycle_used', models.IntegerField(default=0, help_text='Hours already used in current 8-day cycle (0-70)')),
                ('cmv_weight', models.IntegerField(default=10001, help_text='CMV weight in pounds (must be ≥10,001 lbs or placarded hazmat)')),
                ('requires_cdl', models.BooleanField(default=True)),
                ('adverse_conditions', models.BooleanField(default=False)),
                ('includes_hazmat', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EldLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.IntegerField()),
                ('date', models.DateField()),
                ('driving_hours', models.DecimalField(decimal_places=2, max_digits=4)),
                ('on_duty_hours', models.DecimalField(decimal_places=2, max_digits=4)),
                ('off_duty_hours', models.DecimalField(decimal_places=2, max_digits=4)),
                ('sleeper_hours', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('cycle_7day_total', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cycle_8day_total', models.DecimalField(decimal_places=2, max_digits=5)),
                ('requires_restart', models.BooleanField(default=False)),
                ('activities', models.JSONField(default=list)),
                ('remarks', models.JSONField(default=list)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eld_logs', to='trips.trip')),
            ],
            options={
                'ordering': ['trip', 'day_number'],
                'unique_together': {('trip', 'day_number')},
            },
        ),
    ]